ARG MONGOOSE_VERSION

FROM emcmongoose/mongoose-storage-driver-base-service:${MONGOOSE_VERSION}

ADD ["./build/libs/mongoose-storage-driver-hdfs.jar", "/opt/mongoose/ext/mongoose-storage-driver-hdfs.jar"]
